### ISSUE TITLE
Beer-sample index stops at 96 docs (dcp related?)

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/cbft#10]
Hey folks,

maybe I'm doing something wrong, but I tried to create an index that uses DCP + bleve to index my beer-sample bucket on localhost.

When I use the tap one instead of DCP it seems to work (already in the hundreds of docs indexed)

It looks like this (all defaults set I think):

![screen shot 2014-12-05 at 10 13 50](https://cloud.githubusercontent.com/assets/29086/5313355/816e06e0-7c67-11e4-903d-17ad56919b97.png)
![screen shot 2014-12-05 at 10 14 02](https://cloud.githubusercontent.com/assets/29086/5313356/84948484-7c67-11e4-9296-f51d5c472dfc.png)

But the document count is stuck at 93, shouldn't it index all those 7k docs initially?

**Comment by steveyen** [comment]
Current thinking is that perhaps some fixes in cbdatasource might be related...

    https://github.com/couchbase/go-couchbase/commit/2fbb633d1699ee299fe9b5cfef1eea15244bfbd8

Going to close this until it pops up again.
