### ISSUE TITLE
would be nice if cbft didn't require a data directory for first-timers

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#102]
From usability test feedback from James M., it'd be nice if cbft didn't require first-timers to pre-create a data directory beforehand.  Perhaps it can use a /tmp directory?

But, there are issues if the user restarts their cbft, they would lose everything (it chooses to create yet another tmp directory instead of reusing the old directory)?

**Comment by mschoch** [comment]
I don't like the idea of defaulting to temp.  What is the problem with creating "data" if it doesn't exist?  Or using it if it does?  I think this is what ES does.

**Comment by steveyen** [comment]
> What is the problem with creating "data" if it doesn't exist? Or using it if it does?

Ok, going use that then as plan A.

**Comment by steveyen** [comment]
Also from testing with Bin on windows, found that "mkdir -p data" creates a "data" directory and a "-p" directory :-)

**Comment by steveyen** [comment]
cbft now creates the data directory automatically if the user is using the default data directory of "data".
