### ISSUE TITLE
file naming convention feels backwards to me

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/cbft#116]
Typically downloadable packages of software put the project name then the version number.  If you're looking for the download amongst a directory full of files this makes it easier to find, and all versions of the project will be grouped together.

Instead of:

    v0.0.3-0-g6f04f94_cbft.darwin.amd64.tar.gz

I would expect:

    cbft-0.0.3-0-g6f04f94.darwin.amd64.tar.gz

**Comment by steveyen** [comment]
Made a Makefile change, which will get tested on the next release (v0.0.4)...

commit 77313a72

**Comment by steveyen** [comment]
Tested it just now with v0.0.4 release, the "best rest ever".
