### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#122]
Looks like it's in cbdatasource...

panic: send on closed channel

goroutine 2497 [running]:
github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).sendStreamReq(0xc20817a000, 0xc208e25320, 0x32, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1314 +0x74e
github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).handleRecv(0xc20817a000, 0xc208e25320, 0xc208e01b90, 0xc208e83a40, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1073 +0xe46
github.com/couchbase/go-couchbase/cbdatasource.func·007()
	/Users/steveyen/go/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:904 +0x57a
created by github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker
	/Users/steveyen/go/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:926 +0x10c2

**Comment by steveyen** [comment]
More info: this was using an experimental pindex implementation (the "DCR" type), so probably is related to bugs there.

**Comment by mschoch** [comment]
True, but it would be great to know that even a buggy server (other end of cbdatasource) can't cause a crash.  i,e. the safety of this library shouldn't depend on correctness of the other side.

**Comment by steveyen** [comment]
Turns out it was indeed a cbdatasource bug: http://review.couchbase.org/#/c/50459/
