### ISSUE TITLE
cbft internal API's aren't propagating CAS and other mutation metadata

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#123]
This might be important if users one day with to index the mutation's metadata like flags, expiration timestamp, and/or CAS number.

But, it's very important for things like cbmirror.

**Comment by daschl** [comment]
@steveyen also the ID, or is this covered separately?

**Comment by steveyen** [comment]
Hi @daschl, the ID should be covered already as the "Key" parameter in the internal cbft various API's.

**Comment by daschl** [comment]
good to know, thanks!

**Comment by steveyen** [comment]
propagating extras... commit 62a9bac

**Comment by steveyen** [comment]
propagating CAS... commit f1a6fa3
