### ISSUE TITLE
for pindex implementations that aren't queryable or countable, don't show the query tab or doc count controls

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#124]
Some "index partition" types (e.g. blackhole type) aren't queryable or countable, so we should dynamically hide the Query tab and the Document Count field in the web admin UI.

**Comment by mschoch** [comment]
What does it mean to be queryable?  Won't different pindex impls support different kinds of queries?  How can these be plugged in?

**Comment by steveyen** [comment]
Have a handwave answer here...

During startup, each pindex implementation registers itself with a cbft, providing metadata and handler funcs for counting, querying, and more.  Here's an example of how the bleve pindex impl registers itself...

    https://github.com/couchbaselabs/cbft/blob/master/pindex_impl_bleve.go#L111

What I was thinking was that some implementations might one day want to just register nil for their count and query handler funcs.  And then the web UI can then hide relevant UI parts based on that.

For different kinds of web UI, though, more UI related stuff might one day need to be registered (maybe paths to HTML templates and/or JS?).  I'd kinda started this on the JS side, too, where I was imagining that future pindex implementations could supply their own "prepQueryRequest()"  implementations, but didn't finish that yet...

    https://github.com/couchbaselabs/cbft/blob/master/static/js/query.js#L5

**Comment by steveyen** [comment]
commit 1195aae hides the query tab and doc count based on metadata on pindex impl type capabilities.
