### ISSUE TITLE
Correct 0.2.0 cbft server start exception message

### ISSUE THREAD

**Issue by weilliu** [couchbaselabs/cbft#154]
0.2.0 cbft-full start returns the same "not a URL " error message under the following circumstance
- without preexisting default bucket 
- omit username and password on URL 
- wrong username and password on URL

```
[root@centos-58 cbft]# ./cbft-full.linux.amd64 -server=http://Administrator:psword@10.3.3.203:8091
2015/07/16 14:02:14 main: ./cbft-full.linux.amd64 started (v0.2.0-0-g9179ac8/3.1.0)
2015/07/16 14:02:14   -bindHttp="0.0.0.0:8095"
....
....
2015/07/16 14:02:14 FATAL: error: not a URL, server: "http://Administrator:psword@10.3.3.203:8091"
  Please check that your -server parameter is a valid URL
  (http://HOST:PORT), such as "http://localhost:8091",
  to a couchbase server -- main.main() at main.go:142
```

**Comment by steveyen** [comment]
see commit 4d5c41e

**Comment by steveyen** [comment]
With that fix, the output error message now looks like...

2015/07/17 08:25:53 FATAL: error: could not connect to server ("http://foo:bar@localhost:8091"), err: HTTP error 401 Unauthorized getting "http://localhost:8091/pools": 
  Please check that your -server parameter ("http://foo:bar@localhost:8091")
  is correct, the couchbase server is accessible,
  and auth is correct (e.g., http://USER:PSWD@HOST:PORT) -- main.main() at main.go:143
