### ISSUE TITLE
queries containing vbucket/seqno requirements should not block forever

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/cbft#17]
Had a chat with @vmx about this today.  He suggested that instead of the request blocking until it can be satisfied, it should return immediately with the currently available sequence numbers.

This way the client can decide what to do.  It can block while retrying, it could give some indication of how long the wait might be, etc.

It also avoids holding resources open between the client and server during the wait.

**Comment by steveyen** [comment]
Looking at this again after awhile, the client can do this today by passing in a low timeout value... like 1 millisecond.  Then cbft will timeout and provide the current seq-number of the vbucket as part of its error response.
