### ISSUE TITLE
feature: ability to query subset of partitions

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#171]
Inspired from ElasticSearch, what if a node is down, and the user favors availability over correctness of results for their particular application.

Then, there should be a way to inform cbft during a query that not having all servers up and running is ok.

Then the results might include metadata like "was able to get results from 3 out of 5 index partitions".

**Comment by mcpaddy** [comment]
Couchbase Server ( I suspect it's from CouchDB) had the same thing with onError response from view queries.

**Comment by steveyen** [comment]
Going to close this one in couchbaselabs/cbft, as I've been trying to shrink couchbaselabs/cbft issues is obsoleted and main issue tracking is now either moved to JIRA or to couchbase/cbft (for internal TODO's)

https://issues.couchbase.com/browse/MB-17014
