### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/cbft#176]
2015/09/03 11:48:13 FATAL: error: not a URL, server: "http://localhost:8091"
  Please check that your -server parameter is a valid URL
  (http://HOST:PORT), such as "http://localhost:8091",
  to a couchbase server -- main.main() at main.go:142
 
This seems weird, since I was using the exact same command line I had been before.
 
It turns out the message means "Couchbase Server isn't running"

**Comment by steveyen** [comment]
This might have been fixed with latest/master, as the line number no longer matches, and I see a different err msg.  Note: this was when manually launched, not launched using the toy/watson build...

Launched with simple Cfg provider...

    $ ./cbft -server=http://localhost:8091
    ...
    2015/09/04 09:40:05 FATAL: error: could not connect to server ("http://localhost:8091"), err: Get http://localhost:8091/pools: dial tcp 127.0.0.1:8091: connection refused
      Please check that your -server parameter ("http://localhost:8091")
      is correct, the couchbase server is accessible,
      and auth is correct (e.g., http://USER:PSWD@HOST:PORT) -- main.main() at main.go:158

When launched with the couchbase bucket Cfg provider...

    $ ./cbft -cfg=couchbase:http://cfg-auth:password@localhost:8091 -server=http://127.0.0.1:8091 -bindHttp=192.168.59.3:9090 -data=data0 -tags=feed,janitor,pindex,queryer
    2015/09/04 09:37:38 main: ./cbft started (v0.2.0-105-ge878a7a/4.0.0)
    ...
    2015/09/04 09:37:38 FATAL: main: could not start cfg, cfgConnect: couchbase:http://cfg-auth:password@localhost:8091, err: Get http://localhost:8091/pools: dial tcp 127.0.0.1:8091: connection refused
      Please check that your -cfg/-cfgConnect parameter ("couchbase:http://cfg-auth:password@localhost:8091")
      is correct and/or that your configuration provider
      is available. -- main.main() at main.go:135

Versions of cbft/cbgt...

    $ git describe
    v0.2.0-105-ge878a7a
    $ (cd ../cbgt && git describe)
    v0.2.0-208-gb721c2c
