### ISSUE TITLE
boltdb error "key too large"

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#33]
I've seen cases recently where reports a repeated "key too large" (aside: you can see cbft's been configured with a 20 second retry backoff)...

    2015/03/17 16:30:17 feed_dcp: OnError, name: intrapop.1_7b714b8c18fe53ec: bucketName: default, bucketUUID: , err: error: HandleRecv, err: key too large
    2015/03/17 16:30:37 feed_dcp: OnError, name: intrapop.1_7b714b8c18fe53ec: bucketName: default, bucketUUID: , err: error: HandleRecv, err: key too large
    2015/03/17 16:30:57 feed_dcp: OnError, name: intrapop.1_7b714b8c18fe53ec: bucketName: default, bucketUUID: , err: error: HandleRecv, err: key too large

The current guess is that it might be related to boltdb key length error...

    https://github.com/boltdb/bolt/blob/master/errors.go#L57

...where perhaps recent changes in bleve encodings might be related.

Error messages probably need improving as a secondary thing here.

**Comment by steveyen** [comment]
made a change to capture more info on the suspect key/seq for next time we see this: dc1eef9

**Comment by mschoch** [comment]
Bolt says,

    MaxKeySize = 32768

**Comment by mschoch** [comment]
Perils of doing this via phone...

Point of comment was we need more info, would not expect to generate a key that large

**Comment by steveyen** [comment]
Another thought: there's a possibility my bleve files were created awhile back before any recent bleve file format encoding changes (if there indeed were any bleve format changes at all -- not sure).

Anyways, after adding more logging output to show the document key/ID, here are some representative log outputs from cbft.

    2015/03/17 17:30:32 feed_dcp: OnError, name: intrapop-play_b3162a27cd309fc2: bucketName: default, bucketUUID: , err: error: DataChange, err: feed_dcp: DataUpdate, name: intrapop-play_b3162a27cd309fc2, partition: 54, key: couchbaselabs/mini-hacks/xamarin/todo-sync/README.md, seq: 5699, err: key too large

I've put the document for that couchbaselabs/mini-hacks/xamarin/todo-sync/README.md over here (memcached ASCII get)...

    https://gist.github.com/steveyen/423bb059d07b16432c1b

Another one...

    2015/03/17 17:30:33 feed_dcp: OnError, name: intrapop-play_b3162a27cd309fc2: bucketName: default, bucketUUID: , err: error: DataChange, err: feed_dcp: DataUpdate, name: intrapop-play_b3162a27cd309fc2, partition: 38, key: couchbaselabs/lcbook/iops.md, seq: 5749, err: key too large

With related doc here...

    https://gist.github.com/steveyen/5ec1a1807edc0ed02a1a

**Comment by steveyen** [comment]
Some more clues...

On one of the nodes, I just blew away the bleve boltdb files and restarted from scratch.  It looks ok after that (no errors).  The 2nd node still has the old files that have the issue, which I'll keep around for a bit just in case.

The bleve mapping config that I'm using is here...

    https://gist.github.com/steveyen/31bcfa738abe7d6060c3

**Comment by mschoch** [comment]
Bleve should refuse to read old formats...

**Comment by mschoch** [comment]
I don't see any way this should generate a key length > 32768 even if the 'contents' field was indexed with the keyword analyzer the whole file is only 22k bytes.

**Comment by steveyen** [comment]
At this point, not sure how to get cbft into a state where this happens reproducibly.

Related, with the improvements that were part of https://github.com/couchbaselabs/cbft/issues/35, we should hopefully be able to have some better error messages for when/if the next time this happens.

So, closing this until we see it again.

**Comment by steveyen** [comment]
I added more fmt.Printf()'s to the boltdb KVStore implementation, and the key indeed is too large when it attempts during a Batch Execute() to Put() the output of Merge()'ed data...

    https://github.com/blevesearch/bleve/blob/master/index/store/boltdb/batch.go#L87

I've gist'ed up some more detailed info (the mapping, the doc, the log output) here... 

    https://gist.github.com/steveyen/073d757093b73d521248

**Comment by steveyen** [comment]
By the way, it seems to work ok while using the leveldb KVStore instead of the boltdb KVStore, in where I'd guess that leveldb doesn't have a key size limit.

**Comment by mschoch** [comment]
OK, this helps some, but we still don't understand why this is happening.  The offending key is a dictionary entry, since the first byte of key is 'd'.  The next two bytes are the field "\r\x00", so this is field 13.  The remaining bytes are the term.  It appears to be garbage.  I thought perhaps it was base64 encoded, but it does not decode to anything less garbagey.  Is there any reason you included that one particular README?  Since it occurs on a dictionary entry, we don't know which item in the batch triggered it.  Can we get all the doc ids in the batch and review all of them?  Also, if you have the database, run bleve_dump -fields so we can see which field is number 13, that might also give a clue.

**Comment by steveyen** [comment]
On the README, I had some other logging that showed me what document key might have been the issue.  But, now that I think about it, I might have gotten that wrong due to the Batch semantics, and the doc ID that was logged is probably not the true problematic doc.

I'll soon add some more logging to get all doc ID's from the batch.

In the meanwhile, from the bleve_dump -fields, looks like field 13 is the "_all" field...

$ ./bleve_dump -index data/intrapop-leveldb.1_5837ca03b3a96619_acbbef99.pindex/ -fields
Field: 1 Name: commit
Key:   66 01 00                                                                                            
Value: 63 6f 6d 6d 69 74 ff                                                                                

Field: 2 Name: repo
Key:   66 02 00                                                                                            
Value: 72 65 70 6f ff                                                                                      

Field: 3 Name: type
Key:   66 03 00                                                                                            
Value: 74 79 70 65 ff                                                                                      

Field: 4 Name: id
Key:   66 04 00                                                                                            
Value: 69 64 ff                                                                                            

Field: 5 Name: url
Key:   66 05 00                                                                                            
Value: 75 72 6c ff                                                                                         

Field: 6 Name: parentId
Key:   66 06 00                                                                                            
Value: 70 61 72 65 6e 74 49 64 ff                                                                          

Field: 7 Name: author
Key:   66 07 00                                                                                            
Value: 61 75 74 68 6f 72 ff                                                                                

Field: 8 Name: authorFacet
Key:   66 08 00                                                                                            
Value: 61 75 74 68 6f 72 46 61 63 65 74 ff                                                                 

Field: 9 Name: authorDate
Key:   66 09 00                                                                                            
Value: 61 75 74 68 6f 72 44 61 74 65 ff                                                                    

Field: 10 Name: message
Key:   66 0a 00                                                                                            
Value: 6d 65 73 73 61 67 65 ff                                                                             

Field: 11 Name: key
Key:   66 0b 00                                                                                            
Value: 6b 65 79 ff                                                                                         

Field: 12 Name: commitDate
Key:   66 0c 00                                                                                            
Value: 63 6f 6d 6d 69 74 44 61 74 65 ff                                                                    

Field: 13 Name: _all
Key:   66 0d 00                                                                                            
Value: 5f 61 6c 6c ff                                                                                      

Field: 14 Name: merge
Key:   66 0e 00                                                                                            
Value: 6d 65 72 67 65 ff                                                                                   

Field: 15 Name: contents
Key:   66 0f 00                                                                                            
Value: 63 6f 6e 74 65 6e 74 73 ff                                                                          

Field: 16 Name: project
Key:   66 10 00                                                                                            
Value: 70 72 6f 6a 65 63 74 ff                                                                             

Field: 17 Name: ext
Key:   66 11 00                                                                                            
Value: 65 78 74 ff                                                                                         

Field: 18 Name: title
Key:   66 12 00                                                                                            
Value: 74 69 74 6c 65 ff                                                                                   

Field: 19 Name: spaceKey
Key:   66 13 00                                                                                            
Value: 73 70 61 63 65 4b 65 79 ff                                                                          

Field: 20 Name: creationDate
Key:   66 14 00                                                                                            
Value: 63 72 65 61 74 69 6f 6e 44 61 74 65 ff                                                              

Field: 21 Name: lastModifierName
Key:   66 15 00                                                                                            
Value: 6c 61 73 74 4d 6f 64 69 66 69 65 72 4e 61 6d 65 ff                                                  

Field: 22 Name: lastModificationDate
Key:   66 16 00                                                                                            
Value: 6c 61 73 74 4d 6f 64 69 66 69 63 61 74 69 6f 6e 44 61 74 65 ff                                      

Field: 23 Name: bodyContent
Key:   66 17 00                                                                                            
Value: 62 6f 64 79 43 6f 6e 74 65 6e 74 ff                                                                 

Field: 24 Name: creatorName
Key:   66 18 00                                                                                            
Value: 63 72 65 61 74 6f 72 4e 61 6d 65 ff                                                                 

Field: 25 Name: branch
Key:   66 19 00                                                                                            
Value: 62 72 61 6e 63 68 ff                                                                                

Field: 26 Name: updatedDate
Key:   66 1a 00                                                                                            
Value: 75 70 64 61 74 65 64 44 61 74 65 ff                                                                 

Field: 27 Name: createdDate
Key:   66 1b 00                                                                                            
Value: 63 72 65 61 74 65 64 44 61 74 65 ff                                                                 

Field: 28 Name: owner
Key:   66 1c 00                                                                                            
Value: 6f 77 6e 65 72 ff                                                                                   

Field: 29 Name: change_id
Key:   66 1d 00                                                                                            
Value: 63 68 61 6e 67 65 5f 69 64 ff                                                                       

Field: 30 Name: status
Key:   66 1e 00                                                                                            
Value: 73 74 61 74 75 73 ff

**Comment by steveyen** [comment]
Again, I find out the computer is not lying to me.  The offending doc indeed has a token (term? word?) that is indeed too large... basically a base64 encoded lorem hunk of text with no whitespace...

https://gist.github.com/steveyen/b912499ec2b59daf58a6

**Comment by steveyen** [comment]
Copy & pasting some hints from chat with Marty on how to get a filter for max token length...

step 1, you need to define your own analyzer that copies the default one you're already using

step 2 insert a length filter, with whatever max token length you want.  the length fliter lets you specify min/max token length

**Comment by steveyen** [comment]
A custom token length filter did the trick.  No more "key too large" errors from boltdb.

commit 49c01a
