### ISSUE TITLE
cbft cmd-line error output is too verbose

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#48]
when user invokes cbft with an unknown cmd-line flag, cbft dumps out the entire usage help string in an attempt to be helpful.

but, that help string obscures the actual error message and is too noisy, so instead cbft should just emit the specific cmd-line flag message only.

**Comment by steveyen** [comment]
looks like this is fundamental to how flag package works and trying to get a newline in there is hard without rewriting golang's flag parsing code.

**Comment by mschoch** [comment]
You can override the usage function... not sure if that would help: https://github.com/couchbaselabs/cbgb/blob/53841e4a2179428e1968e4154d1797a2503ecf0a/main.go#L99

**Comment by steveyen** [comment]
thanks - that helped!

commit 0716475
