### ISSUE TITLE
cbft uses couchbaselabs/goforestdb instead of couchbase/goforestdb

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#58]
From the cbft manifests, I see cbft's using couchbaselabs/goforestdb.  Which one's the right one?

**Comment by mschoch** [comment]
They are the same.  The project was moved to "couchbase", and "couchbaselabs" now redirects.  You should switch to "couchbase" as that is the canonical name, and I've heard reports that the redirects don't always play nice with the go tools.

**Comment by steveyen** [comment]
Saw from bleve commit b54a591 that this was fixed.
