### ISSUE TITLE
consider switching to from go-manifest to godep, gb, etc

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/cbft#6]
I haven't used it yet myself, but it appears to be functionally very similar, with the benefit it that is being used by others in the go community.

https://github.com/tools/godep

**Comment by steveyen** [comment]
Hat-tip to Marty, looks like there even a newer thing, gb, that might be the eventual winner.

Lazily, I think we should let it all settle down in the go community first before switching.

**Comment by steveyen** [comment]
Or, it looks like the laziest, leading maneuver is to await new golang 1.5 related features.

**Comment by mschoch** [comment]
There is also the issue that once we begin integration with Couchbase server, the repo file will be the authoritative source of locked revisions and cloned repos.

Some thought should be given to how (if?) this will be supported for use outside of Couchbase server.

**Comment by steveyen** [comment]
As I'm scrubbing old bugs, I think this is close'able as no need to do anything more.

afaik, we've been able to maintain build'ability via standalone cbft via standard "go get", and also optionally with more build tags (such as what we do via Makefile).

And, the manifests / repo approach of Couchbase Server integrated builds seems to also work.

Going to 1.5, too, and picking up whatever vendoring that provides, will just be the natural, expected par for the course if we need vendoring, so I figure we don't need a ticket to remind us about that.
