### ISSUE TITLE
cbft should have distinction between bind addr and registration host/port identifier

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbft#97]
right now, cbft overloads the -bindHttp command-line parameter for both uses.

But, the user might want to bind to 0.0.0.0, but still be known as some different host/port identifier.

Maybe use some [BIND/]HOST:PORT syntax... for example: "0.0.0.0/cbft-01.dc-west-01:9090"

**Comment by steveyen** [comment]
This separation of bindAddr usage (no longer using bindAddr as a unique node registration idenitifier) was done as part of https://github.com/couchbaselabs/cbft/issues/169.

Related, if we still want the 0.0.0.0 network address binding mentioned above, then we should open a clearer issue ticket just for that.

**Comment by mschoch** [comment]
Its fairly common for servers to let you configure 2 separate addresses, a bind host and a publish host.

Here is the relevant section of the Elasticsearch docs: https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules-network.html

**Comment by mschoch** [comment]
I've opened a separate ticket since this one is closed.
