### ISSUE TITLE
cbft require Couchbase Version 3 or greater 

### ISSUE THREAD

**Issue by mcpaddy** [couchbaselabs/cbft#99]
I believe CBFT makes use of DCP which is only available in Couchbase server 3 or great. Worth adding a note to the README.

**Comment by mcpaddy** [comment]
I will do a pull request later.

**Comment by mschoch** [comment]
Technically, this requirement is only for the DCP feed.  Other feeds have different requirements.  This is the tip of the iceberg where cbft has to decide if its general purpose, or specifically streamlined for Couchbase.

**Comment by steveyen** [comment]
A related issue (perhaps duplicate)... https://github.com/couchbaselabs/cbft/issues/67

**Comment by steveyen** [comment]
Hi, I made some docs, README and cmd-line fixes recently to add a mention of needing Couchbase "3.x".

**Comment by steveyen** [comment]
(scrubbing bugs... gonna close this as the README mentions this now)
